### ISSUE TITLE
can't install electron

### ISSUE THREAD

**Issue by JisunGia** [actinoide/albion-crafting-calculator#2]
when i type npm install -g electron in cmd it does not finish succesfully and when i type npm start in the main dir it give me an error

![image](https://github.com/actinoide/albion-crafting-calculator/assets/112628354/4d71f869-590f-4e82-aad7-fd31aa1dccb5)

![image](https://github.com/actinoide/albion-crafting-calculator/assets/112628354/587b4386-7d99-4871-9fd6-614d2eabe545)

**Comment by actinoide** [comment]
This seems to be an electron related issue and not something specific to this program, maybe see if the electron docs can help you out: https://www.electronjs.org/docs/latest/tutorial/installation.

**Comment by actinoide** [comment]
This seems to be an electron related issue and not something specific to this program, maybe see if the electron docs can help you out: https://www.electronjs.org/docs/latest/tutorial/installation.
